# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{chimps-cli}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dhruv Bansal"]
  s.date = %q{2011-03-25}
  s.default_executable = %q{chimps}
  s.description = %q{Chimps CLI provides the command line program 'chimps' which allows you to easily make API calls against Infochimps web services.}
  s.email = %q{coders@infochimps.com}
  s.executables = ["chimps"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/chimps",
    "lib/chimps-cli.rb",
    "lib/chimps-cli/commands.rb",
    "lib/chimps-cli/commands/base.rb",
    "lib/chimps-cli/commands/create.rb",
    "lib/chimps-cli/commands/delete.rb",
    "lib/chimps-cli/commands/destroy.rb",
    "lib/chimps-cli/commands/download.rb",
    "lib/chimps-cli/commands/get.rb",
    "lib/chimps-cli/commands/help.rb",
    "lib/chimps-cli/commands/list.rb",
    "lib/chimps-cli/commands/me.rb",
    "lib/chimps-cli/commands/post.rb",
    "lib/chimps-cli/commands/put.rb",
    "lib/chimps-cli/commands/query.rb",
    "lib/chimps-cli/commands/search.rb",
    "lib/chimps-cli/commands/show.rb",
    "lib/chimps-cli/commands/test.rb",
    "lib/chimps-cli/commands/update.rb",
    "lib/chimps-cli/commands/upload.rb",
    "lib/chimps-cli/utils.rb",
    "lib/chimps-cli/utils/acts_on_resource.rb",
    "lib/chimps-cli/utils/explicit_path.rb",
    "lib/chimps-cli/utils/http_format.rb",
    "lib/chimps-cli/utils/uses_param_value_data.rb",
    "spec/chimps-cli/commands/delete_spec.rb",
    "spec/chimps-cli/commands/get_spec.rb",
    "spec/chimps-cli/commands/help_spec.rb",
    "spec/chimps-cli/commands/list_spec.rb",
    "spec/chimps-cli/commands/post_spec.rb",
    "spec/chimps-cli/commands/put_spec.rb",
    "spec/chimps-cli/commands/show_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/acts_on_resource.rb",
    "spec/support/explicit_path.rb",
    "spec/support/http_format.rb",
    "spec/support/uses_param_value_data.rb"
  ]
  s.homepage = %q{http://github.com/infochimps/chimps-cli}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Chimps CLI is command-line interface for the Chimps gem (http://www.infochimps.com/labs)}
  s.test_files = [
    "spec/chimps-cli/commands/delete_spec.rb",
    "spec/chimps-cli/commands/get_spec.rb",
    "spec/chimps-cli/commands/help_spec.rb",
    "spec/chimps-cli/commands/list_spec.rb",
    "spec/chimps-cli/commands/post_spec.rb",
    "spec/chimps-cli/commands/put_spec.rb",
    "spec/chimps-cli/commands/show_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/acts_on_resource.rb",
    "spec/support/explicit_path.rb",
    "spec/support/http_format.rb",
    "spec/support/uses_param_value_data.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<chimps>, [">= 0.3.1"])
      s.add_runtime_dependency(%q<configliere>, [">= 0.3.2"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
    else
      s.add_dependency(%q<chimps>, [">= 0.3.1"])
      s.add_dependency(%q<configliere>, [">= 0.3.2"])
      s.add_dependency(%q<json>, [">= 0"])
    end
  else
    s.add_dependency(%q<chimps>, [">= 0.3.1"])
    s.add_dependency(%q<configliere>, [">= 0.3.2"])
    s.add_dependency(%q<json>, [">= 0"])
  end
end

